AUGMENTATION: True
INPUT_SHAPE: [150, 150, 3] # as per Xception model
IMAGE_SIZE: [150, 150]
BATCH_SIZE: 8
INCLUDE_TOP: False
EPOCHS: 3
WEIGHTS: imagenet
LEARNING_RATE: 0.0001
OFFSET: -1
VALIDATION_SPLIT: 0.10
TRAIN_SPLIT: 0.70
TEST_SPLIT: 0.20
