AUGMENTATION: True
IMAGE_SIZE: [150, 150, 3] # as per Xception model
BATCH_SIZE: 64
INCLUDE_TOP: False
EPOCHS: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.001
OFFSET: -1
VALIDATION_SPLIT: 0.20
TRAIN_SPLIT: 0.50
TEST_SPLIT: 0.30
