artifacts_root: artifacts


data_ingestion:
  local_data_file: artifacts/datasets/farm_copilot_dataset


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras

